# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  # virtualisation.hypervGuest.enable = true;

  fileSystems."/mnt/ssd" = {
    device = "/dev/disk/by-id/ata-SanDisk_SSD_PLUS_1000GB_214401A00277-part1";
    fsType = "auto";
    options = [ "nofail" ];
  };

  fileSystems."/mnt/hdd" = {
    device = "/dev/mapper/ubuntu--vg-home--lv";
    fsType = "auto";
    options = [ "nofail" ];
  };
}
